#!/bin/bash

# Washlee Order Flow Diagnostic Script
# Run this after making a test payment to identify where orders are failing

echo "================================================"
echo "Washlee Order Flow Diagnostic Tool"
echo "================================================"
echo ""
echo "This script will help you diagnose order issues after payment."
echo ""
echo "STEP 1: Check Your Recent Orders in Firestore"
echo "================================================"
echo ""
echo "1. Go to: https://console.firebase.google.com"
echo "2. Select your project: 'Washlee' (or your project name)"
echo "3. Click 'Firestore Database' in the left sidebar"
echo "4. Look for these collections:"
echo ""
echo "   A) Check 'orders' collection:"
echo "      - Should see: order-1707614XXX-abc123def (recent timestamp)"
echo "      - Each order should have:"
echo "        ✓ orderId"
echo "        ✓ uid (your Firebase user ID)"
echo "        ✓ email"
echo "        ✓ amount"
echo "        ✓ status: 'confirmed'"
echo "        ✓ estimatedWeight"
echo "        ✓ deliverySpeed"
echo "        ✓ createdAt (recent time)"
echo ""
echo "   B) Check 'users/{YOUR_UID}' document:"
echo "      - Look for your user ID in the users collection"
echo "      - Should have these fields:"
echo "        ✓ email"
echo "        ✓ orders (ARRAY) <- Most important!"
echo "        ✓ lastOrderId"
echo "        ✓ lastOrderDate"
echo ""
echo "      - The 'orders' array should contain:"
echo "        ✓ orderId"
echo "        ✓ email"
echo "        ✓ amount"
echo "        ✓ status"
echo "        ✓ createdAt"
echo ""
echo "================================================"
echo "STEP 2: Check Server Logs"
echo "================================================"
echo ""
echo "Look at the terminal where you ran 'npm run dev'"
echo ""
echo "You should see messages like:"
echo ""
echo "✓ GOOD (successful payment):"
echo "  [Webhook] Received event: checkout.session.completed"
echo "  [Webhook] Processing laundry booking completion: { uid: '...', orderId: '...', email: '...' }"
echo "  [Firebase] Order created in orders collection: order-1707614XXX"
echo "  [Firebase] ✓ Order synced to customer account: YOUR_UID"
echo ""
echo "✗ BAD (something went wrong):"
echo "  [Webhook] Missing uid in session metadata"
echo "  [Firebase] Error creating order:"
echo "  [Firebase] Error syncing to customer account:"
echo ""
echo "================================================"
echo "STEP 3: Check Browser Console"
echo "================================================"
echo ""
echo "1. Go to http://localhost:3000/dashboard/customer"
echo "2. Press F12 to open Developer Tools"
echo "3. Click the 'Console' tab"
echo "4. Look for messages like:"
echo ""
echo "✓ GOOD:"
echo "  [Dashboard] Fetching orders with auth token"
echo "  [Dashboard] Orders API response status: 200"
echo "  [Dashboard] Got orders: 1"
echo ""
echo "✗ BAD:"
echo "  [Dashboard] Error fetching orders: Failed to load orders"
echo "  [Dashboard] Error fetching orders: Unauthorized"
echo "  [Dashboard] Error: Cannot read property 'orders' of undefined"
echo ""
echo "================================================"
echo "STEP 4: Check What Should Appear on Dashboard"
echo "================================================"
echo ""
echo "If everything worked, the dashboard should show:"
echo ""
echo "Active Orders:"
echo "├── [Order ID: order-1707614XXX]"
echo "│   ├── Status: Confirmed"
echo "│   ├── Weight: X kg"
echo "│   ├── Delivery: Standard"
echo "│   ├── Address: Your delivery address"
echo "│   └── Price: $XX.XX"
echo "└── [More orders...]"
echo ""
echo "================================================"
echo "STEP 5: Common Issues & Fixes"
echo "================================================"
echo ""
echo "ISSUE 1: Order in Firestore but NOT in user.orders array"
echo "├─ Cause: User document doesn't exist yet"
echo "├─ Fix: Create a 'users' document with your uid first"
echo "└─ Check: Does user document have 'orders' field?"
echo ""
echo "ISSUE 2: No order appears in Firestore at all"
echo "├─ Cause: Webhook never received the event"
echo "├─ Check: Does server log show 'checkout.session.completed'?"
echo "└─ Fix: Check that Stripe webhook is configured correctly"
echo ""
echo "ISSUE 3: Order shows in Firebase but NOT in dashboard"
echo "├─ Cause: Dashboard query field mismatch"
echo "├─ Fix: Dashboard now uses /api/orders/user/{uid} endpoint"
echo "└─ Check: Browser console for API error messages"
echo ""
echo "ISSUE 4: 'uid is not defined' in console"
echo "├─ Cause: Not logged in or uid not passed correctly"
echo "├─ Fix: Make sure you're logged in with Firebase auth"
echo "└─ Check: user.uid exists in /booking page"
echo ""
echo "================================================"
echo "STEP 6: Test Payment Flow"
echo "================================================"
echo ""
echo "To test, use this Stripe test card:"
echo "  Card: 4242 4242 4242 4242"
echo "  Expiry: 12/34"
echo "  CVC: 123"
echo ""
echo "Steps:"
echo "1. Go to http://localhost:3000/booking"
echo "2. Fill out the form (address, weight, delivery type, etc.)"
echo "3. Click 'Confirm & Pay'"
echo "4. Fill in test card details above"
echo "5. Click 'Pay'"
echo "6. You should see success page with real order ID (not temp-...)"
echo "7. Go to /dashboard/customer"
echo "8. Refresh and order should appear"
echo ""
echo "================================================"
echo "STEP 7: Verify Complete Flow"
echo "================================================"
echo ""
echo "Check these in order:"
echo ""
echo "[✓] User logged in with Firebase"
echo "[✓] Booking page shows user.uid in console"
echo "[✓] Stripe checkout created (check server logs)"
echo "[✓] Webhook received event (check server logs: 'checkout.session.completed')"
echo "[✓] Order created in orders collection (check Firestore)"
echo "[✓] Order synced to user.orders array (check Firestore user document)"
echo "[✓] lastOrderId updated on user (check Firestore user document)"
echo "[✓] Dashboard API returns orders (check browser console)"
echo "[✓] Dashboard displays order (should see in Active Orders tab)"
echo ""
echo "================================================"
echo "STEP 8: If Still Not Working"
echo "================================================"
echo ""
echo "Run these debugging commands:"
echo ""
echo "# Check server logs for errors"
echo "grep -i 'error' ~/.pm2/logs/* 2>/dev/null | tail -20"
echo ""
echo "# Verify Firestore connection"
echo "firebase use --list"
echo ""
echo "# Check if Firebase emulator is interfering"
echo "ps aux | grep -i emulator | grep -v grep"
echo ""
echo "# Verify API endpoint is accessible"
echo "curl -X GET 'http://localhost:3000/api/orders/user/YOUR_UID' -H 'Authorization: Bearer YOUR_TOKEN'"
echo ""
echo "================================================"
echo "Questions to Answer:"
echo "================================================"
echo ""
read -p "1. Do you see 'checkout.session.completed' in server logs? (y/n) " webhook_log
read -p "2. Does 'orders' collection exist in Firestore? (y/n) " orders_exist
read -p "3. Do you have a 'users' collection in Firestore? (y/n) " users_exist
read -p "4. Does your user document have an 'orders' field? (y/n) " user_orders_field
read -p "5. Does browser console show '[Dashboard] Got orders: X'? (y/n) " dashboard_orders
echo ""
echo "Based on your answers:"
if [ "$webhook_log" != "y" ]; then
    echo "❌ Webhook not firing - check Stripe webhook endpoint configuration"
fi
if [ "$orders_exist" != "y" ]; then
    echo "❌ Orders collection missing - webhook didn't create order"
fi
if [ "$users_exist" != "y" ]; then
    echo "❌ Users collection missing - need to create user documents"
fi
if [ "$user_orders_field" != "y" ]; then
    echo "❌ User document missing 'orders' field - need to add it manually"
fi
if [ "$dashboard_orders" != "y" ]; then
    echo "❌ Dashboard not fetching orders - check API or auth token"
fi
echo ""
echo "================================================"
echo "Done! Review the checks above to fix issues."
echo "================================================"
